### ISSUE TITLE
Berserker Mod Crash (Sinytra Connector [Forge])

### ISSUE THREAD

**Issue by GonKiIlua** [ProfessorFichte/Berserker-RPG-Class#4]
Hi, I don't know if you're developing for Sinytra Connector in mind, but this class mod crashes with this error (the other classes don't crash)
[Berserker Crash log.txt](https://github.com/user-attachments/files/15965008/Berserker.Crash.log.txt)

**Comment by ProfessorFichte** [comment]
Greetings, I did not plan to support Synitra Connectar Issues that much. But according to your crash log it seems
net/spell_engine/api/item/weapon/MeleeWeaponItem is the issue which i´m using for my Items, I will look what i can do.

**Comment by ProfessorFichte** [comment]
@GonKiIlua Could you please show me which mod versions you use? In your crashlog I cant see which versions your mods are, I think your Spell Engine Mod is not up to date
